config/routes.rb
Rails.application.routes.draw do
  resources :clients
  devise_for :users, path: 'user', controllers: {
    sessions: 'devise_users/sessions',
    passwords: 'devise_users/passwords',
    registrations: 'devise_users/registrations'
  }
  resources :users

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'frontend#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, :last_name, :phone, presence: true
  validates :email, format: { with: /@/ }, allow_blank: true
  validates :first_name, :last_name, :phone, length: {maximum: 50, allow_empty: true}
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  validates :first_name, :last_name, length: { in: 2..30 }, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :phone, :country, :city, :birthday, :occupation, :gender)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/devise_users/passwords_controller.rb
class DeviseUsers::PasswordsController < Devise::PasswordsController
  layout 'login', only: [:new]

  def new
    super
  end
end

app/controllers/devise_users/registrations_controller.rb
class DeviseUsers::RegistrationsController < Devise::RegistrationsController
  layout 'login'
end

app/controllers/devise_users/sessions_controller.rb
class DeviseUsers::SessionsController < Devise::SessionsController
  layout 'login', only: [:new]

  def new
    super
  end

  private

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  layout "frontend"
  before_action :redirect_to_dashboard_if_user_singed_in

  def index
  end

  private

  def redirect_to_dashboard_if_user_singed_in
    redirect_to authenticated_root_path if user_signed_in?
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'login', only: [:new]

  def new
    super
  end

  private

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @users = User.page(params[:page]).includes(:roles).order('created_at DESC').per_page(25)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    if UserService.new.create_user(user_params)
      flash[:notice] = I18n.t('messages.user.created')
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = I18n.t('messages.user.updated')
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def replace_flash_key(key)
    {alert: 'danger', notice: 'info'}[key.to_sym] || key
  end

  def user_assigned_roles(user=nil)
    user ||= current_user
    user.roles.collect(&:name).join(', ')
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.slim
= simple_form_for(@client) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :phone
    = f.input :country, only: ["UA"]
    = f.input :city
    = f.input :birthday, start_year: Date.today.year - 90,
      end_year: Date.today.year - 12, order: [:day, :month, :year]
    = f.input :occupation
    = f.collection_radio_buttons :gender, [[true, t('gender.male')] ,[false, t('gener.female')]], :first, :last

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to t('basic.cancel'), :back, class: 'btn btn-default'

app/views/clients/edit.html.slim
h1 Editing client

== render 'form'

= link_to 'Show', @client
'|
= link_to 'Back', clients_path

app/views/clients/index.html.slim
.box
  .box-header
    = link_to 'New Client', new_client_path, class: 'btn btn-primary'

  .box-body.no-padding
    table.table.table-striped
      thead
        th First name
        th Last name
        th Phone
        th Country
        th City
        th
        th
        th

      tbody
        - @clients.each do |client|
          tr
            td = client.first_name
            td = client.last_name
            td = client.phone
            td = client.country
            td = client.city
            td = link_to t('basic.show'), client_path(client), class: 'btn btn-xs btn-info'
            td = link_to t('basic.edit'), edit_client_path(client), class: 'btn btn-xs btn-primary'
            td = link_to t('basic.destroy'), client, class: 'btn btn-xs btn-danger',
              data: { confirm: t('basic.act_confirm') }, method: :delete

app/views/clients/new.html.slim
h1 New client

== render 'form'

app/views/clients/show.html.slim
p#notice = notice

p
  strong First name:
  = @client.first_name
p
  strong Last name:
  = @client.last_name
p
  strong Email:
  = @client.email
p
  strong Phone:
  = @client.phone
p
  strong Country:
  = @client.country
p
  strong City:
  = @client.city
p
  strong Birthday:
  = @client.birthday
p
  strong Occupation:
  = @client.occupation
p
  strong Gender:
  = @client.gender

= link_to 'Edit', edit_client_path(@client)
'|
= link_to 'Back', clients_path

app/views/dashboard/index.html.slim
h1 Dashboard#index
p Find me in app/views/dashboard/index.html.slim

app/views/frontend/index.html.slim
header
  .header-content
    .header-content-inner
      h1 Your Favorite Source of Free Bootstrap Themes
      hr/
      p Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!
      a.btn.btn-primary.btn-xl.page-scroll href="#about"  Find Out More
section#about.bg-primary
  .container
    .row
      .col-lg-8.col-lg-offset-2.text-center
        h2.section-heading We've got what you need!
        hr.light/
        p.text-faded Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!
        a.page-scroll.btn.btn-default.btn-xl.sr-button href="#services"  Get Started!
section#services
  .container
    .row
      .col-lg-12.text-center
        h2.section-heading At Your Service
        hr.primary/
  .container
    .row
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-diamond.text-primary.sr-icons
          h3 Sturdy Templates
          p.text-muted Our templates are updated regularly so they don't break.
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-paper-plane.text-primary.sr-icons
          h3 Ready to Ship
          p.text-muted You can use this theme as is, or you can make changes!
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-newspaper-o.text-primary.sr-icons
          h3 Up to Date
          p.text-muted We update dependencies to keep things fresh.
      .col-lg-3.col-md-6.text-center
        .service-box
          i.fa.fa-4x.fa-heart.text-primary.sr-icons
          h3 Made with Love
          p.text-muted You have to make your websites with love these days!
section#portfolio.no-padding
  .container-fluid
    .row.no-gutter.popup-gallery
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/1.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/2.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/3.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/4.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/5.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
      .col-lg-4.col-sm-6
        = link_to '#', class: 'portfolio-box' do
          = image_tag 'creative/portfolio/fullsize/6.jpg', class: 'img-responsive'
        .portfolio-box-caption
          .portfolio-box-caption-content
            .project-category.text-faded
              | Category
            .project-name
              | Project Name
aside.bg-dark
  .container.text-center
    .call-to-action
      h2 Free Download at Start Bootstrap!
      a.btn.btn-default.btn-xl.sr-button href="http://startbootstrap.com/template-overviews/creative/"  Download Now!
section#contact
  .container
    .row
      .col-lg-8.col-lg-offset-2.text-center
        h2.section-heading Let's Get In Touch!
        hr.primary/
        p Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!
      .col-lg-4.col-lg-offset-2.text-center
        i.fa.fa-phone.fa-3x.sr-contact
        p 123-456-6789
      .col-lg-4.text-center
        i.fa.fa-envelope-o.fa-3x.sr-contact
        p
          a href="mailto:your-email@your-domain.com"  feedback@startbootstrap.com

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  div class=("alert alert-#{replace_flash_key(key)}") 
    a.close data-dismiss="alert" href="#"  ×
    ul
      li
        = value

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title WorkAbroad
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'admin-lte', mdeia: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin-lte', 'data-turbolinks-track': 'reload'

  body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      /! Main Header
      header.main-header
        /! Logo
        = link_to root_path, class: 'logo' do
          span.logo-mini Work Abroad
          span.logo-lg Work Abroad
        /! Header Navbar
        nav.navbar.navbar-static-top role="navigation"
          /! Sidebar toggle button
          a.sidebar-toggle data-toggle="offcanvas" href="#" role="button"
            span.sr-only Toggle navigation
          /! Navbar Right Menu
          .navbar-custom-menu
            ul.nav.navbar-nav
              /! User Account Menu
              li.dropdown.user.user-menu
                /! Menu Toggle Button
                a.dropdown-toggle data-toggle="dropdown" href="#"
                  /! The user image in the navbar
                  = image_tag "adminlte2/user2-160x160.jpg", class: 'user-image'
                  span.hidden-xs
                    = current_user.full_name
                ul.dropdown-menu
                  /! The user image in the menu
                  li.user-header
                    = image_tag "adminlte2/user2-160x160.jpg", class: 'img-circle'
                    p
                      = current_user.full_name
                      |  -
                      = user_assigned_roles
                      small Member since Nov. 2012
                  /! Menu Body
                  li.user-body
                    .row
                      .col-xs-4.text-center
                        a href="#"  Followers
                      .col-xs-4.text-center
                        a href="#"  Sales
                      .col-xs-4.text-center
                        a href="#"  Friends
                    /! /.row
                  /! Menu Footer
                  li.user-footer
                    .pull-left
                      = link_to 'Profile', edit_user_registration_path, class: 'btn btn-default btn-flat'
                    .pull-right
                      = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'
      /! Left side column. contains the logo and sidebar
      aside.main-sidebar
        /! sidebar: style can be found in sidebar.less
        section.sidebar
          /! Sidebar user panel (optional)
          .user-panel
            .pull-left.image
              = image_tag "adminlte2/user2-160x160.jpg", class: 'img-circle'
            .pull-left.info
              p = current_user.full_name
              /! Status
              a href="#"
                i.fa.fa-circle.text-success
                | Online
          /! search form (Optional)
          form.sidebar-form action="#" method="get"
            .input-group
              input.form-control name="q" placeholder="Search..." type="text" /
              span.input-group-btn
                button#search-btn.btn.btn-flat name="search" type="submit"
                  i.fa.fa-search
          /! /.search form
          /! Sidebar Menu
          ul.sidebar-menu
            li.header HEADER
            /! Optionally, you can add icons to the links
            li.active
              = link_to authenticated_root_path do
                i.fa.fa-link
                span = t 'main_menu.dashboard'
            li
              = link_to users_path do
                i.fa.fa-link
                span = t 'main_menu.users'
            li
              = link_to clients_path do
                i.fa.fa-link
                span = t 'main_menu.clients'

          /! /.sidebar-menu
        /! /.sidebar
      /! Content Wrapper. Contains page content
      .content-wrapper
        = render 'layouts/messages'
        /! Content Header (Page header)
        section.content-header
          h1
            | Page Header
            small Optional description
          ol.breadcrumb
            li
              a href="#"
                i.fa.fa-dashboard
                | Level
            li.active Here
        /! Main content
        section.content
          = yield
        /! /.content
      /! /.content-wrapper
      /! Main Footer
      footer.main-footer
        /! To the right
        .pull-right.hidden-xs
          | Anything you want
        /! Default to the left
        strong
          | Copyright &copy; 2015 Company All rights reserved.

app/views/layouts/frontend.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="" name="description" /
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title WorkAbroad
    = csrf_meta_tags
    = stylesheet_link_tag    'frontend', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'frontend', 'data-turbolinks-track': 'reload'
    /! Custom Fonts
    link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" /
    link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css" /
  body#page-top
    nav#mainNav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        /! Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand.page-scroll href="#page-top"  Start Bootstrap
        /! Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            li
              a.page-scroll href="#about"  About
            li
              a.page-scroll href="#services"  Services
            li
              a.page-scroll href="#portfolio"  Portfolio
            li
              a.page-scroll href="#contact"  Contact
        /! /.navbar-collapse
      /! /.container-fluid
    = yield

app/views/layouts/login.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title WorkAbroad
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body.hold-transition.login-page
    = render 'layouts/messages'
    = yield

app/views/users/_user.html.slim
tr
  td= link_to '#'+user.id.to_s, user_path(user)
  td= user.first_name
  td= user.last_name
  td= user.email
  td= user_assigned_roles user

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
.box
  .box-header
    h3.box-title Striped Full Width Table
  /! /.box-header
  .box-body.no-padding
    table.table.table-striped
      tr
        th style=("width: 10px")  #
        th =t 'users.first_name'
        th =t 'users.last_name'
        th =t 'users.email'
        th =t 'users.roles'
      = render @users
    = will_paginate @users 

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim

app/views/users/show.html.slim
h1
  = @user.full_name
= @user.email